server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Sirve archivos estáticos
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Acepta headers y redirecciones del proxy de EasyPanel
    location /_health {
        access_log off;
        default_type text/plain;
        return 200 "OK";
    }
}
